repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^(data/|stage3/lib/RooDoubleCB)
    -   id: end-of-file-fixer
        exclude: ^(data/|stage3/lib/RooDoubleCB)
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: ^tests/samples/
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: ^(data/|stage3/lib/RooDoubleCB)
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: ^(data/|stage3/lib/RooDoubleCB)
