name: ci

on:
  push:
    branches: [ run3_prototype ]
  pull_request:
    branches: [ run3_prototype ]

  workflow_dispatch:

jobs:
  validation_stage1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    name: stage1

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install packages
        run: |
          python3 -m pip install --user --upgrade -r requirements.txt
      - name: run stage 1
        run: python3 -W ignore tests/test_stage1.py

  validation_stage2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    name: stage2

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install packages
        run: |
          python3 -m pip install --user --upgrade -r requirements.txt
      - name: run stage 2
        run: python3 -W ignore tests/test_stage2.py

  validation_continuous:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    name: continuous

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install packages
        run: |
          python3 -m pip install --user --upgrade -r requirements.txt
      - name: run continuous (stages 1 & 2)
        run: python3 -W ignore tests/test_continuous.py
