name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    name: build - flake8 - python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install flake8
        run: python -m pip install -q flake8
      - name: flake8 - check ./*py
        run: flake8 ./*py
      - name: flake8 - check python/*py
        run: flake8 python/*py

