name: nanoaod continuous

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  validation_latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    name: nanoaod continuous

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install packages
        run: |
          python -m pip install coffea
          python -m pip install dask[distributed]
      - name: continuous (stages 1 & 2)
        run: python -W ignore tests/test_nanoaod_continuous.py
