name: nanoaod

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  validation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    name: separate (latest coffea)

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install packages
        run: |
          python3 -m pip install --user --upgrade -r requirements.txt
      - name: stage 1
        run: python3 -W ignore tests/test_nanoaod_stage1.py
      - name: stage 2
        run: python3 -W ignore tests/test_nanoaod_stage2.py

  validation_continuous:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    name: continuous (latest coffea)

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install packages
        run: |
          python3 -m pip install --user --upgrade -r requirements.txt
      - name: continuous (stages 1 & 2)
        run: python3 -W ignore tests/test_nanoaod_continuous.py
